Parameters:
    BucketName:
        Type: String
        Description: "Name of the Log Bucket"
        MinLength: 1
        MaxLength: 80
        Default: "sns-message-logs-2024"

Resources:
    LogsBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketEncryption:
                ServerSideEncryptionConfiguration:
                    - ServerSideEncryptionByDefault:
                          SSEAlgorithm: aws:kms
                          KMSMasterKeyID: !ImportValue "KmsKeyArn"
            BucketName: !Ref BucketName
            LifecycleConfiguration:
                Rules:
                    - Id: LogsRetention
                      Prefix: log
                      Status: Enabled
                      ExpirationInDays: 1
            Tags:
                - Key: Requirement
                  Value: SnsMessagesLogging
                - Key: Type
                  Value: Logs
    LogsBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref LogsBucket
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          AWS: !Ref "AWS::AccountId"
                      Action:
                          - "s3:PutObject"
                          - "s3:GetObject"
                      Resource:
                          !Join ["", ["arn:aws:s3:::", !Ref BucketName, "/*"]]
                    - Effect: Allow
                      Principal:
                          Service:
                              - "s3.amazonaws.com"
                      Action:
                          - "s3:ListBucket"
                      Resource: !Join ["", ["arn:aws:s3:::", !Ref BucketName]]

Outputs:
    BucketName:
        Description: "Name of the Log Bucket"
        Value: !Ref BucketName
        Export:
            Name: "BucketName"
    BucketArn:
        Description: "Arn of the Log Bucket"
        Value: !GetAtt LogsBucket.Arn
        Export:
            Name: "BucketArn"
